// FROZEN CONTRACT
// Date:    2026-06-13
// Project: MPDS-MCP — Multi Project Design System MCP Server
// Module:  webui (C-webui)
//
// This file is the single authoritative TypeScript interface contract for the
// C-webui human-facing web editor. It defines:
//   1. UI state interfaces
//   2. data-testid string helpers (TestIds)
//   3. The API client interface that C-webui uses to talk to C-mcp REST
//   4. Accepted color format annotation
//
// C-webui communicates EXCLUSIVELY with C-mcp via /api/* REST endpoints.
// It never calls C-tokens, C-components, or C-registry directly.
//
// Do NOT edit this file without going through the contract change process
// (re-lint, breaking-change detection, and re-freeze). All builders implement
// against this frozen surface.

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Debounce delay (ms) applied to both the live preview update and the
 *  WCAG contrast check triggered by token value edits. (REQ-024, REQ-026) */
export const DEBOUNCE_MS = 300;

// ---------------------------------------------------------------------------
// Color format
// ---------------------------------------------------------------------------

/**
 * The only accepted color formats for token value input (REQ-023).
 * Values that do not match one of these three patterns MUST be rejected
 * client-side before any save or preview action is triggered.
 *
 * Accepted patterns:
 *   #RGB       — three-digit hex shorthand, e.g. #f0a
 *   #RRGGBB    — six-digit hex, e.g. #ff0033
 *   rgb(R,G,B) — functional notation, integers 0-255, e.g. rgb(255, 0, 51)
 *
 * All other formats (hsl, oklch, named colors, etc.) are rejected.
 */
export type AcceptedColorFormat = string;

/** Runtime guard — test a raw string against this before saving or previewing. */
export const COLOR_FORMAT_RE =
  /^(#[0-9a-fA-F]{3}|#[0-9a-fA-F]{6}|rgb\(\s*\d{1,3}\s*,\s*\d{1,3}\s*,\s*\d{1,3}\s*\))$/;

// ---------------------------------------------------------------------------
// Inline minimal API-level types
// (mirror only the fields C-webui reads/writes from the C-mcp OpenAPI contract)
// ---------------------------------------------------------------------------

/** A project in the registry. */
export interface Project {
  id: string;
  name: string;
  parentId?: string;
  createdAt: string;
}

/** A single resolved token value (base merged with project overrides). */
export interface ResolvedToken {
  key: string;
  category: string;
  value: string;
  source: "base" | "override";
  isSemantic: boolean;
  semanticRef?: string;
  /**
   * Version integer forwarded as the If-Match header value on PUT (REQ-028).
   */
  version: string;
}

/** A single resolved component spec (base merged with project overrides). */
export interface ResolvedComponentSpec {
  id: string;
  name: string;
  variants: string[];
  states: string[];
  accessibilityNotes: string;
  usageRules: string;
  hasOverride: boolean;
}

/** Payload for PUT .../components/{componentId}/override. */
export interface ComponentOverrideInput {
  usageRules?: string;
  variants?: string[];
}

/** Response from POST /api/validate/color-pair. */
export interface ContrastResult {
  pairId: string;
  foreground: string;
  background: string;
  ratio: number;
  requiredRatio: number;
  passes: boolean;
}

/** An AI-proposed change (P3). */
export interface Proposal {
  id: string;
  projectId: string;
  targetType: "token" | "component";
  targetKey: string;
  proposedValue: string;
  rationale: string;
  status: "pending" | "approved" | "rejected";
  createdAt: string;
}

/** An audit record for a proposal decision (P3). */
export interface ProposalAuditRecord {
  proposalId: string;
  action: "approved" | "rejected";
  note?: string;
  decidedAt: string;
}

// ---------------------------------------------------------------------------
// 1. Project UI state
// ---------------------------------------------------------------------------

/**
 * Represents one row in the project selector list (REQ-022).
 * Rendered with data-testid="project-item-{id}".
 * When selected: aria-selected="true" + data-testid="project-item-selected".
 */
export interface ProjectListItem {
  id: string;
  name: string;
  parentId?: string;
  selected: boolean;
}

/**
 * Local form state for the "new project" modal/panel (REQ-022).
 * Input bound to data-testid="project-name-input".
 * Submit button bound to data-testid="new-project-btn".
 */
export interface NewProjectFormState {
  name: string;
  parentId?: string;
  submitting: boolean;
  error?: string;
}

// ---------------------------------------------------------------------------
// 2. Token UI state
// ---------------------------------------------------------------------------

/**
 * Per-row UI state for the token editor (REQ-023, REQ-024, REQ-025, REQ-028).
 *
 * Rendered with:
 *   data-testid="token-row-{key}"
 *   data-source="base" | "override"
 *
 * `editValue` is present only while the row is in editing mode.
 * `isDirty` is true when editValue !== value.
 * `previewVisible` gates rendering of data-testid="token-preview".
 * `previewError` is set when the value is not a valid AcceptedColorFormat;
 *   triggers data-testid="preview-error" and disables the save button.
 * `saveError` is set on a 409 CONFLICT response from PUT (REQ-028);
 *   triggers data-testid="save-error" with "conflict" text.
 */
export interface TokenRowState {
  key: string;
  category: string;
  value: string;
  source: "base" | "override";
  isSemantic: boolean;
  semanticRef?: string;
  version: string;
  editValue?: string;
  isDirty: boolean;
  isEditing: boolean;
  previewVisible: boolean;
  previewError?: string;
  saveError?: string;
}

/**
 * Per-pair WCAG badge state (REQ-026).
 *
 * Rendered as:
 *   data-testid="wcag-badge-fail-{pairId}"  when passes === false
 *   data-testid="wcag-badge-pass-{pairId}"  when passes === true
 *
 * Populated from ContrastResult; persists after save.
 */
export interface WcagBadgeState {
  pairId: string;
  passes: boolean;
  ratio: number;
  requiredRatio: number;
}

// ---------------------------------------------------------------------------
// 3. Component UI state
// ---------------------------------------------------------------------------

/**
 * Per-field override form state for the component spec editor (REQ-027).
 *
 * Overridden fields carry data-overridden="true".
 * Revert button: data-testid="component-revert-{componentId}-{field}".
 */
export interface ComponentOverrideFormState {
  componentId: string;
  field: string;
  originalValue: string | string[];
  editValue: string | string[];
  submitting: boolean;
  error?: string;
}

// ---------------------------------------------------------------------------
// 4. TestIds helper
// ---------------------------------------------------------------------------

/**
 * Typed const object that generates data-testid strings matching the
 * requirements spec. Import in both component code and tests for
 * refactor-safe, single-source-of-truth testid strings.
 *
 * Usage:
 *   <div data-testid={TestIds.tokenRow("color.primary")} />
 *   screen.getByTestId(TestIds.tokenRow("color.primary"))
 */
export const TestIds = {
  // REQ-022: Project selector
  projectItem: (id: string) => `project-item-${id}` as const,
  projectItemSelected: "project-item-selected" as const,
  newProjectBtn: "new-project-btn" as const,
  projectNameInput: "project-name-input" as const,
  emptyProjectsState: "empty-projects-state" as const,

  // REQ-023: Token browse & override
  tokenRow: (key: string) => `token-row-${key}` as const,
  colorSwatch: (key: string) => `color-swatch-${key}` as const,
  tokenValueInput: "token-value-input" as const,

  // REQ-024: Live preview
  tokenPreview: "token-preview" as const,
  previewError: "preview-error" as const,

  // REQ-025: Inheritance indicator
  baseValue: (key: string) => `base-value-${key}` as const,
  tokenRevert: (key: string) => `token-revert-${key}` as const,
  filterOverridesOnly: "filter-overrides-only" as const,

  // REQ-026: Inline WCAG feedback
  wcagBadgeFail: (pairId: string) => `wcag-badge-fail-${pairId}` as const,
  wcagBadgePass: (pairId: string) => `wcag-badge-pass-${pairId}` as const,

  // REQ-027: Component spec browse & override
  componentItem: (id: string) => `component-item-${id}` as const,
  componentName: "component-name" as const,
  componentVariants: "component-variants" as const,
  componentStates: "component-states" as const,
  componentAccessibilityNotes: "component-accessibility-notes" as const,
  componentUsageRulesInput: "component-usage-rules-input" as const,
  componentVariantsInput: "component-variants-input" as const,
  componentRevert: (cid: string, field: string) =>
    `component-revert-${cid}-${field}` as const,

  // REQ-028: Save overrides OCC
  saveError: "save-error" as const,

  // REQ-033 (P3): Approval queue
  proposalQueue: "proposal-queue" as const,
  approveProposal: (id: string) => `approve-proposal-${id}` as const,
  rejectProposal: (id: string) => `reject-proposal-${id}` as const,
  rejectionNoteInput: "rejection-note-input" as const,
} as const;

// ---------------------------------------------------------------------------
// 5. WebUiApiClient — the C-mcp REST client interface
// ---------------------------------------------------------------------------

/**
 * The API client interface that C-webui must implement (or inject) to
 * communicate with C-mcp. All methods are async. C-webui MUST NOT call
 * C-tokens, C-components, or C-registry directly.
 *
 * Implementations should map HTTP errors to thrown Error instances with a
 * `.status` number property so callers can distinguish 409 CONFLICT from
 * other errors.
 */
export interface WebUiApiClient {
  // Projects
  listProjects(): Promise<Project[]>;
  createProject(name: string, parentId?: string): Promise<Project>;
  getProject(projectId: string): Promise<Project>;
  deleteProject(projectId: string): Promise<void>;

  // Tokens
  listTokens(projectId: string, category?: string): Promise<ResolvedToken[]>;

  /**
   * PUT /api/projects/{projectId}/tokens/{key}
   *
   * OCC (REQ-028): `ifMatch` must be the `version` from the last-fetched
   * ResolvedToken and is sent as the HTTP `If-Match` header.
   * On 409 CONFLICT, the implementation throws an error with `.status === 409`.
   * The UI then renders data-testid="save-error" with "conflict" text (REQ-028).
   */
  upsertTokenOverride(
    projectId: string,
    key: string,
    value: string,
    ifMatch: string,
  ): Promise<ResolvedToken>;

  deleteTokenOverride(projectId: string, key: string): Promise<ResolvedToken>;

  // Components
  listComponents(projectId: string): Promise<ResolvedComponentSpec[]>;
  getComponent(projectId: string, componentId: string): Promise<ResolvedComponentSpec>;
  upsertComponentOverride(
    projectId: string,
    componentId: string,
    input: ComponentOverrideInput,
  ): Promise<ResolvedComponentSpec>;
  deleteComponentOverride(projectId: string, componentId: string): Promise<ResolvedComponentSpec>;

  /**
   * POST /api/validate/color-pair
   *
   * ALWAYS an API call — never computed client-side (REQ-026).
   * Called on the DEBOUNCE_MS debounce, same window as the live preview.
   * Badge state persists after save; it is NOT cleared on successful PUT.
   */
  validateColorPair(
    pairId: string,
    foreground: AcceptedColorFormat,
    background: AcceptedColorFormat,
  ): Promise<ContrastResult>;

  // Proposals (P3)
  listProposals(projectId: string): Promise<Proposal[]>;
  listAuditRecords(projectId: string): Promise<ProposalAuditRecord[]>;
  approveProposal(proposalId: string): Promise<Proposal>;
  /**
   * @param note  Optional rejection rationale bound to
   *              data-testid="rejection-note-input" (REQ-033).
   */
  rejectProposal(proposalId: string, note?: string): Promise<Proposal>;
}
